taxi_transformation:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      database: TAXI_DEV
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DE_DEV_ROLE
      schema: BRONZE
      threads: 4
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: TAXI_WH
    prod:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: DE_PROD_ROLE
      database: TAXI_PROD
      warehouse: TAXI_WH
      schema: BRONZE
      threads: 8  # More threads for prod performance    
  target: dev
