name: dbt_Continuous_Integration

on:
  push:
    branches: [ main ]  # Runs every time you push to main
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-snowflake
          dbt deps

      - name: Run dbt Build (Dev Environment)
        env:
          # This maps the GitHub Secret to an Environment Variable
          DBT_ENV_SECRET_PASSWORD: ${{ secrets.DBT_SNOWFLAKE_PASSWORD }}
        run: |
          # We run build against 'dev' to ensure the new code doesn't break anything
          # dbt will use the Env Var for the password in your profiles.yml
          dbt build --project-dir taxi_transformation --profiles-dir taxi_transformation --target prod
